### PR TITLE
Package-ify

### PR DESCRIPTION
**Pull request by ric-evans**
closes https://github.com/WIPACrepo/file-catalog-indexer/issues/43

### CODE REVIEW

**Review by dsschult — COMMENTED** [review]
Seems generally fine.  I guess my only question (maybe long-term) is if we want scripts in the root directory or if we want python modules, like `python -m indexer` or `python -m indexer.delocator`.

**Comment by ric-evans** [comment]
> Seems generally fine. I guess my only question (maybe long-term) is if we want scripts in the root directory or if we want python modules, like `python -m indexer` or `python -m indexer.delocator`.

I can throw them into `indexer/scripts`, so `python -m indexer.scripts.delocator`. The scripts need `indexer` installed anyway, so they might as well come with the package.

**Comment by ric-evans** [comment]
> I'm not sure how much I like the `/scripts` directory pattern. Is there a reason why a
> 
> ```python
> if __name__ == '__main__':
>    # parse args and call func
> ```
> 
> block can't be added to the end of a library file? I've found good use with that pattern in a couple projects, where you usually use something as a library but occasionally call it directly for debugging or expert fixing of something.

I find these can be confusing if you don't know the package well. What's a script, what's a module? This could be fixed by a README, or perhaps naming them using verbs: `delocate`, `index`, `generate`. Thoughts?

**Comment by dsschult** [comment]
Documentation of course always helps :smile: 

Using verbs is an interesting concept.  I'd approve.

**Review by dsschult — APPROVED** [review]

**Pull request merged**
