### PR TITLE
Filename pattern finder

### PR DESCRIPTION
**Pull request by ric-evans**
Added a script which redacts numerical sub-strings with a single `#`. Then, it aggregates the results to find common filename patterns. Some numerical substrings are preserved, like `i3` and `level2`.

### CODE REVIEW

**Review by dsschult — COMMENTED** [review]
One note: `str.replace()` is faster than `re.sub()` and should be preferred whenever it's a simple replacement.

**Comment by ric-evans** [comment]
> One note: `str.replace()` is faster than `re.sub()` and should be preferred whenever it's a simple replacement.

That's true but I didn't think there was a way to do `re.sub(r'\d+', '#')` with `str.replace()`

**Comment by dsschult** [comment]
Yeah, that one is probably faster with `re.sub` since it actually uses regex matches.

**Comment by ric-evans** [comment]
> Yeah, that one is probably faster with `re.sub` since it actually uses regex matches.

oh I forgot about the other subs. Yes that would improve performance quite a bit

**Pull request merged**
