### PR TITLE
Publish to PyPI

### PR DESCRIPTION
**Pull request by ric-evans**
closes https://github.com/WIPACrepo/file-catalog-indexer/issues/42

### CODE REVIEW

**Comment by ric-evans** [comment]
@blinkdog I'm assuming you want to enable telemetry for this, so I'm requiring `wipac-rest-tools[telemetry]`. Let me know if this is incorrect.

**Comment by ric-evans** [comment]
waiting on https://github.com/WIPACrepo/iceprod/issues/307 and https://github.com/WIPACrepo/file_catalog/issues/127

**Comment by ric-evans** [comment]
> @blinkdog I'm assuming you want to enable telemetry for this, so I'm requiring `wipac-rest-tools[telemetry]`. Let me know if this is incorrect.

Actually, this won't matter. `wipac-file-catalog` requires telemetry anyways, so it'll already be there

**Comment by ric-evans** [comment]
prev commit should read "bump `WIPACrepo/wipac-dev-py-setup-action`"

**Comment by ric-evans** [comment]
looks like https://github.com/WIPACrepo/file_catalog/pull/129 has a bug in it

**Comment by dsschult** [comment]
I think LGTM is now flagging unsafe yaml loading.  Maybe replace with
```
in_yaml = yaml.safe_load(f)
```

**Review by dsschult — APPROVED** [review]

**Pull request merged**
